[Add] Zeus module for assigning player's a loadout manually.
Bubbus/F3_CA_BUB pull request #164
Opened 2023-06-13 20:01 UTC by BAXENdev

### Pull Request Description
This adds a new zeus function that lets the zeus assign a player a specific loadout. Mainly useful for loadout issues in the middle of a mission.

### Release Notes
Added a zeus function that gives a player a loadout from the gearscript.

## IMPORTANT

- [x] Testing has been completed as neccessary, depending on the nature & impact of the changes.
- [x] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [x] If the contribution affects [the wiki](https://github.com/CombinedArmsGaming/CAFE3/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [x] [Contribution Guidelines](https://github.com/CombinedArmsGaming/CAFE3/blob/release/contributing.md) are read, understood and applied.
- [x] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

2023-06-14 15:01 UTC, Cre8or requested changes
Some changes needed.

The function fails on other players (see my other comment). Additionally, the naming convention needs unifying:
- the function is called `zen_assignGear`,
- the ZEN module is called "Give Loadout",
- the dialog title reads "ASSIGN LOADOUT".

Personally, I'm in favour of sticking with the expression "assign loadout" for all use cases, as it best reflects the intention (and behaviour) of the module.

2023-06-14 15:01 UTC, Cre8or commented on components/gearScript/zen/fn_zen_assignGear.sqf
> +    [_typeOfUnit,_unit] call f_fnc_assignGear;
Attempting to use this module on any player unit other than your own will fail. This is because [`f_fnc_assignGear` takes a local unit as argument.](https://github.com/CombinedArmsGaming/CAFE3/blob/develop/components/gearScript/fn_assignGear.sqf#L21)

I see two ways to solve this:
- either error out and display a message when attempting to use the module on remote units (thus making it only work on local units (player + local AI units), which would be silly), or
- use `remoteExecCall` to call `f_fnc_assignGear` on the unit's owning machine (preferred, as this will allow it to work on *any* unit; local or remote (note: other players are always remote)).

For future reference, you can (and should) test this in a locally hosted multiplayer session. Start a second instance of the game and use that as a second (remote) player, then you can perform (most) locality tests without requiring a dedicated server.

2023-06-15 05:15 UTC, BAXENdev commented on components/gearScript/zen/fn_zen_assignGear.sqf
> +    [_typeOfUnit,_unit] call f_fnc_assignGear;
I tested in multiplayer environment, but it was faulty. Never knew about being able to open a second instance. That helps a lot. All issues have been resolved.

2023-06-15 09:51 UTC, Cre8or reviewed
Better, but I'd still prefer `zen_assignGear` to be renamed to `zen_assignLoadout` as explained in my last review. I can be convinced to keep it this way, as the underlying function is indeed called `f_fnc_assignGear`, but I personally value consistency within this module more.

 @Bubbus - thoughts?

2023-06-15 12:20 UTC, BAXENdev commented
Oh, missed that. Quick update ASAP.

2023-06-15 12:50 UTC, Joecuronium requested changes
When renaming the file you need to update the function names in the .hpp and the module as well.

2023-06-15 14:37 UTC, Cre8or approved these changes
Yup, looks good to me now.

2023-08-14 22:11 UTC, closed without merging