[Feature] Added slotting generator.
Bubbus/F3_CA_BUB pull request #209
Opened 2024-04-17 18:23 UTC by Bubbus

Resolves #131 

### Pull Request Description
**When merged this pull request will:**
- Add a generator for slotting website JSON into the framework.
- Add a ZEN module to run the slotting generator and a configuration file to turn it on and off.

### Release Notes
Added a way to automatically generate slotting code for the mission slotting website!  To learn more, see the new `slottingGenerator.hpp` file in the `configuration` folder.

## IMPORTANT

- [x] Testing has been completed as neccessary, depending on the nature & impact of the changes.
- [x] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [ ] If the contribution affects [the wiki](https://github.com/CombinedArmsGaming/CAFE3/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [x] [Contribution Guidelines](https://github.com/CombinedArmsGaming/CAFE3/blob/release/contributing.md) are read, understood and applied.
- [x] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-05-22 12:34 UTC, Cre8or requested changes
Overall a very useful QoL feature; it took me some time to figure it out (as I've never dealt with slotting data before) but it seems to work as expected. Only noteworthy issue I found is the DLC detection stub - not sure whether that's intentional, an oversight or still a WIP.

Also, I'm not sure if this has been discussed, but what are your thoughts on modifying the `mission.sqm` to support the slotting generator module out-of-the-box? As it stands, users still have to:
- mark the overall commander (using `this setVariable ["f_leaderGroup", true]`), and
- link all of their groups together (using the "Sync to" feature)

for this PR to work. We can make their life easier by doing all of this ahead of time. This will gain even more importance once we add the other side presets back in (OPFOR/INDFOR slots). Maybe something to add to #211?

2024-05-22 12:34 UTC, Cre8or commented on components/slottingGenerator/fn_discoverAllUnitDLCs.sqf
Is this function intentionally blank?

2024-05-22 12:34 UTC, Cre8or commented on components/slottingGenerator/fn_composeJSONUnknownFragments.sqf
> +				if ((count _sampleContent == 2) and ((typeName (_sampleContent#0)) == "STRING")) exitWith
Use `isEqualType` over manual type comparisons: 

```suggestion
				if ((count _sampleContent == 2) and {(_sampleContent#0) isEqualType ""}) exitWith 
```

Also note the use of `{}` for [short-circuit evaluation](https://community.bistudio.com/wiki/a_and_b), to ensure that we are always dereferencing an array index that is valid.

2024-05-27 08:52 UTC, Bubbus commented on components/slottingGenerator/fn_discoverAllUnitDLCs.sqf
Yep, it's possible with some of the funny new funcs and config lookups, just never got around to it.  I'll throw this into a new ticket cause it's useful to have.

2024-05-27 08:55 UTC, Bubbus commented
> Also, I'm not sure if this has been discussed, but what are your thoughts on modifying the `mission.sqm` to support the slotting generator module out-of-the-box?

Yep, that's what #211 is talking about.  When that was written, both PRs were just kinda vibing next to eachother so I couldn't do anything with the sqm cause sqm files do not play well with merge.

2024-05-27 09:26 UTC, Bubbus commented on components/slottingGenerator/fn_discoverAllUnitDLCs.sqf
https://github.com/CombinedArmsGaming/CAFE3/issues/221

2024-06-08 10:03 UTC, Cre8or approved these changes
Works as expected. The DLC detection can be added later, I'm sure we can live without it for now.

:ship:

2024-06-09 09:37 UTC, merged