[Feature] Added hunter-killer ACE action to crew slots of all land and sea vehicles.
Bubbus/F3_CA_BUB pull request #212
Opened 2024-04-18 20:58 UTC by Bubbus

Resolves #142.

### Pull Request Description
**When merged this pull request will:**
- Add hunter-killer ACE action to crew slots of all land and sea vehicles.

### Release Notes
Added hunter-killer ACE action to crew slots.  You can now turn on ACE Hunter-Killer mode when you're crewing a vehicle and use it to point out targets for your gunner.  This action is available in all vehicles that AI Driver is available for.

## IMPORTANT

- [x] Testing has been completed as neccessary, depending on the nature & impact of the changes.
- [x] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [ ] If the contribution affects [the wiki](https://github.com/CombinedArmsGaming/CAFE3/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [x] [Contribution Guidelines](https://github.com/CombinedArmsGaming/CAFE3/blob/release/contributing.md) are read, understood and applied.
- [x] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-04-23 20:19 UTC, Cre8or requested changes
Yet another solid PR - we're approaching pedantic levels of reviewing because everything else is already spot on. 👍 

Thank you!

2024-04-23 20:19 UTC, Cre8or commented on components/aceActions/fn_addHunterKillerActions.sqf
It took me a minute to figure out that the actions don't have anything to do with the driver role/unit. I'm guessing you copied this from the AI driver action? If so, please rename `_driverNotActive` and `_driverActive` to something else (maybe `_isHunterKillerActive` / `_isHunterKillerInactive`?).

2024-04-23 20:19 UTC, Cre8or commented on startup/components/globals/serverGlobals.sqf
Good catch!

2024-04-23 22:18 UTC, Bubbus commented on components/aceActions/fn_addHunterKillerActions.sqf
oops

2024-04-24 06:32 UTC, Cre8or approved these changes
🚢

2024-04-24 10:16 UTC, merged