[Feature] Add Respawn Details Into Briefing
Bubbus/F3_CA_BUB pull request #234
Opened 2024-11-24 22:35 UTC by cow-co

### Pull Request Description
**When merged this pull request will:**
- Add an entry to the briefing, containing the respawn settings for the mission, for the player's side.

### Release Notes
- Under the `Framework` part of the briefing, there is a new `Current Respawn Settings` entry.
- No configuration needed beyond what is already there for the respawn framework.
- Fields that are not defined for the respawn will be marked as "Not set"
- Covers:
  - Respawn mode (friendly-named, eg. `"Timed Waves, with Tickets"`)
  - Respawn Delay
  - Side tickets
  - player tickets

## IMPORTANT

- [x] Testing has been completed as neccessary, depending on the nature & impact of the changes. Tested locally and on the server, for opfor, blufor, indfor, with various commbinations of respawn settings.
- [x] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [x] If the contribution affects [the wiki](https://github.com/CombinedArmsGaming/CAFE3/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [x] [Contribution Guidelines](https://github.com/CombinedArmsGaming/CAFE3/blob/release/contributing.md) are read, understood and applied.
- [x] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-11-24 22:36 UTC, cow-co commented
Addresses Issue #202

2024-11-24 22:36 UTC, cow-co commented
May make another PR for a similar thing, but with medical settings.

2024-11-24 22:39 UTC, cow-co commented on components/briefing/briefings/ca_briefing_respawn.sqf
> +_respawnModeTimedText = str RESPAWN_MODE_TIMED;
Lord forgive me.

2024-11-24 22:39 UTC, cow-co commented on components/briefing/briefings/ca_briefing_respawn.sqf
> +#endif
for I have sinned.

2024-11-30 17:53 UTC, Bubbus requested changes
I don't really see a better way to do this tbh, so good approach.  Few minor things - fix yourself or I will in a year or two.  tyvm

2024-11-30 17:53 UTC, Bubbus commented on components/briefing/briefings/ca_briefing_respawn.sqf
> +_briefing = "";
Use `private` keyword pls

2024-11-30 17:53 UTC, Bubbus commented on components/briefing/macros.hpp
> +#define RESPAWN_MODE_NAME_TIMED "Timed"
Prefer to have these in `respawn_macros.hpp` so they're in the same place as the things they refer to.

2024-12-05 21:21 UTC, Bubbus approved these changes

2024-12-05 21:22 UTC, merged