[Feature] Additional zeus interface actions
Bubbus/F3_CA_BUB pull request #81
Opened 2022-01-04 17:16 UTC by Joecuronium

### Pull Request Description
**When merged this pull request will:**
Add the CAFE Immersive revive to the medical context actions
Move ending config from the description.ext into a endings file in the configuration folder
Allow any number of endings, with custom music and code execution
Endings will be run from Zeus ACE-actions with a dialog to choose the ending
Add a module to Zeus that allow the toogling of AI pathing ability
Closes #66 

### Release Notes
Endings are now defined in configuration\endings.hpp
Ending triggers are removed from the map screen admin menu and added to Zeus ACE-interact
New module to toggle AI pathing ability
New medical context action for immersive revive

## IMPORTANT

- [ ] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [ ] If the contribution affects [the wiki](https://github.com/CombinedArmsGaming/CAFE3/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [ ] [Contribution Guidelines](https://github.com/CombinedArmsGaming/CAFE3/blob/release/contributing.md) are read, understood and applied.
- [ ] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

2022-01-04 17:17 UTC, Joecuronium commented
Wiki commit will be done at work today

2022-01-04 19:31 UTC, Joecuronium commented
Wiki done, please review

2022-01-05 00:01 UTC, Bubbus requested changes, later dismissed
Quite good changes.  I'm here to nitpick it's what I do 🤓

2022-01-05 00:01 UTC, Bubbus commented on components/miscClient/zen/fn_zen_toggleAIPath.sqf
> +private _alreadyDisabled = !(_unit checkAIFeature "PATH");
The docs don't say whether `_unit` can be a non-local argument to the `checkAIFeature` command - it always will be if the unit was not spawned via Zeus interface.  I have observed cases where the Zeus UI doesn't know the proper state of the AI features, so this may be a problem.

Consider moving this check into `f_fnc_toggleAIPath`, so you can avoid the question and also make it so `f_fnc_toggleAIPath` truly does toggle the AI pathing.

2022-01-05 00:01 UTC, Bubbus commented on components/miscClient/zen_modules.sqf
> +        (_objects findIf {isPlayer _x} != -1);
This might be useful upon AI when AI-unconsciousness is enabled, this is a very niche use case though so I don't think this needs to be changed now - let's just make a ticket about it that we can pick up when we have nothing better to do.

2022-01-05 00:01 UTC, Bubbus commented on components/miscShared/fn_toggleAIPath.sqf
> +RUN_LOCAL_TO(_unit,_this,f_fnc_disableAI);
Potential misnaming - this will send the `f_fnc_disableAI` function to `_unit`'s locality instead of `f_fnc_toggleAIPath`.

The arguments are out of order, they should be `RUN_LOCAL_TO(OBJ,FUNC,ARGS)`.  There was the same issue with ordering in some of the Zeus medical functions, you may have copied from there?

2022-01-05 00:01 UTC, Bubbus commented on components/miscShared/fn_toggleAIPath.sqf
> +if (_alreadyDisabled) then
If this function is supposed to set the PATH state instead of toggling it, I would suggest the name `f_fnc_setAIPathing`.

2022-01-05 00:01 UTC, Bubbus commented on components/zeus_ui/fn_addZeusActions.sqf
> +	[]call f_fnc_endingDialog;
spacing ree 📏📏📏

2022-01-05 00:01 UTC, Bubbus commented on components/zeus_ui/fn_endingDialog.sqf
> +}forEach _endingArray;						//iterate Endings and populate dialog arrays
📏

2022-01-05 00:01 UTC, Bubbus commented on components/zeus_ui/fn_endingDialog.sqf
> +  	["Executing Ending %1", _endingClass]call zen_common_fnc_showMessage;
📏

2022-01-05 00:01 UTC, Bubbus commented on components/zeus_ui/fn_endingDialog.sqf
> +[
pls indent properly 👺

2022-01-05 00:01 UTC, Bubbus commented on components/zeus_ui/fn_endingDialog.sqf
> +[]]call zen_dialog_fnc_create;
📏📏📏

2022-01-05 00:01 UTC, Bubbus commented on configuration/endings.hpp
> +	code = systemChat "Mission Broke";		//Code will run
This should probably be a string so that users know they need to give a string for any statements more complex than this.  For example, `code = {_x setDamage 1;} foreach allUnits; systemChat "pogging uncontrollably";` fails to compile.

```
code = "systemChat 'Mission Broke'";	//Code will run - needs to be a string.
```
```suggestion
	code = "systemChat 'Mission Broke'";    // Code will run - should be a string.
```

2022-01-05 00:10 UTC, Joecuronium commented on configuration/endings.hpp
> +	code = systemChat "Mission Broke";		//Code will run
Oh no, I forgor to fix that in the PR...It was already a string at some point

2022-01-05 00:11 UTC, Joecuronium commented on components/miscClient/zen_modules.sqf
> +        (_objects findIf {isPlayer _x} != -1);
Just heal the unit then, problem solved. Let's not overcomplicate things.

2022-01-05 00:12 UTC, Joecuronium commented on components/miscShared/fn_toggleAIPath.sqf
> +RUN_LOCAL_TO(_unit,_this,f_fnc_disableAI);
In renaming the functions 5 times, I missed this thanks. Also yes, it was copied from the medical.

2022-01-05 00:14 UTC, Joecuronium commented on components/miscShared/fn_toggleAIPath.sqf
> +if (_alreadyDisabled) then
With the locality change, it will indeed toggle.

2022-01-05 03:22 UTC, dgibso29 submitted a review, later dismissed
Looks good. No further comments beyond Bubbus' review.

2022-01-05 04:17 UTC, dgibso29 approved these changes

2022-01-05 04:18 UTC, merged